basePath: /api
definitions:
  entity.Category:
    properties:
      createdAt:
        type: string
      id:
        type: string
      name:
        type: string
      shopId:
        type: string
      updatedAt:
        type: string
    type: object
  entity.CreateCategoryInput:
    properties:
      name:
        type: string
    required:
    - name
    type: object
  entity.LoginResponse:
    properties:
      refresh_token:
        type: string
      token:
        type: string
      user:
        $ref: '#/definitions/entity.UserResp'
    type: object
  entity.RefreshResponse:
    properties:
      token:
        type: string
    type: object
  entity.UpdateUserStatusInput:
    properties:
      is_active:
        type: boolean
    required:
    - is_active
    type: object
  entity.User:
    properties:
      created_at:
        type: string
      email:
        type: string
      full_name:
        type: string
      id:
        type: string
      is_active:
        type: boolean
      role_id:
        type: string
      updated_at:
        type: string
      username:
        type: string
    type: object
  entity.UserResp:
    properties:
      fullName:
        type: string
      id:
        type: string
      permissions:
        items:
          type: string
        type: array
      role:
        type: string
      username:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is the API documentation for the Home Market project.
  title: Home Market API
  version: "1.0"
paths:
  /admin/items/{id}/moderate:
    patch:
      consumes:
      - application/json
      description: Sets the status of a specific item to 'inactive' due to policy
        violation (Admin access only).
      parameters:
      - description: Item ID to moderate
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "403":
          description: Forbidden
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      security:
      - ApiKeyAuth: []
      summary: Moderate Item (Set Inactive)
      tags:
      - Admin
  /admin/users:
    get:
      consumes:
      - application/json
      description: Retrieves a list of all users in the system (Admin access only).
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.User'
            type: array
        "403":
          description: Forbidden
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      security:
      - ApiKeyAuth: []
      summary: Get List of All Users
      tags:
      - Admin
  /admin/users/{id}/status:
    patch:
      consumes:
      - application/json
      description: Sets the 'is_active' status of a target user (Admin access only).
      parameters:
      - description: Target User ID
        in: path
        name: id
        required: true
        type: string
      - description: 'Status update (is_active: true/false)'
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/entity.UpdateUserStatusInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "403":
          description: Forbidden
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      security:
      - ApiKeyAuth: []
      summary: Block or Unblock User Account
      tags:
      - Admin
  /auth/login:
    post:
      consumes:
      - application/json
      description: Authenticate a user with username and password, returns access
        and refresh tokens.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.LoginResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
      summary: User Login
      tags:
      - Auth
  /auth/profile:
    get:
      consumes:
      - application/json
      description: Retrieves the current authenticated user's profile details.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.UserResp'
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
      security:
      - ApiKeyAuth: []
      summary: Get User Profile
      tags:
      - Auth
  /auth/refresh:
    post:
      consumes:
      - application/json
      description: Exchanges a valid refresh token for a new access token.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.RefreshResponse'
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
      summary: Refresh Access Token
      tags:
      - Auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Creates a new user account with default 'buyer' role.
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/entity.UserResp'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Register New User
      tags:
      - Auth
  /categories:
    post:
      consumes:
      - application/json
      description: Allows a logged-in seller to create a new category unique to their
        shop.
      parameters:
      - description: Category details (Name)
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/entity.CreateCategoryInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/entity.Category'
        "400":
          description: Invalid input or missing shop
          schema:
            additionalProperties: true
            type: object
        "403":
          description: Forbidden (not seller)
          schema:
            additionalProperties: true
            type: object
        "409":
          description: Conflict (category name already exists)
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      security:
      - ApiKeyAuth: []
      summary: Create New Shop Category
      tags:
      - Category
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
